[package]
name = "treatment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = "0.5.0"
postgres = "0.19.7"
